management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  redis:
    host: localhost
    port: '6379'
  application:
    name: questionservice
  datasource:
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/microservice
  cache:
    type: redis
  cloud:
    config:
      enabled: 'false'
eureka:
  client:
    register-with-eureka: 'true'
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: 'true'
  instance:
    lease-renewal-interval-in-seconds: '30'
server:
  port: '8082'
