management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers,resilience4j
resilience4j:
  circuitbreaker:
    instances:
      questionservice:
        register-health-indicator: 'true'
        sliding-window-size: '5'
        minimum-number-of-calls: '3'
        failure-rate-threshold: '50'
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: '2'
  timelimiter:
    instances:
      questionservice:
        timeout-duration: 3s
spring:
  redis:
    host: localhost
    port: '6379'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: 'true'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/microservice
  cache:
    type: redis
  application:
    name: quizservice
feign:
  circuitbreaker:
    enabled: 'true'
eureka:
  client:
    fetch-registry: 'true'
    register-with-eureka: 'true'
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: '30'
server:
  port: '8081'
